//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LyDataAcces.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidatura
    {
        public int id { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaInscripcion { get; set; }
        public Nullable<int> horasRequeridas { get; set; }
    
        public virtual Candidatura_Aceptada Candidatura_Aceptada { get; set; }
        public virtual Candidatura_Cancelada Candidatura_Cancelada { get; set; }
        public virtual Candidatura_Finalizada Candidatura_Finalizada { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
