//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LyDataAcces.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidatura_Aceptada
    {
        public int idCandidatura { get; set; }
        public Nullable<System.DateTime> fechaAceptacion { get; set; }
        public Nullable<System.DateTime> fechaAcordadaServicio { get; set; }
        public Nullable<int> horasAcordadas { get; set; }
    
        public virtual Candidatura Candidatura { get; set; }
    }
}
