//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LyDataAcces.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <summary>
    /// EFBancoTiempo class.
    /// </summary>
    public partial class EFBancoTiempo : DbContext
    {
        public EFBancoTiempo()
            : base("name=EFBancoTiempo")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidatura> Candidatura { get; set; }
        public virtual DbSet<Candidatura_Aceptada> Candidatura_Aceptada { get; set; }
        public virtual DbSet<Candidatura_Cancelada> Candidatura_Cancelada { get; set; }
        public virtual DbSet<Candidatura_Finalizada> Candidatura_Finalizada { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
